version: '3.9'
services:
  api_products:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysqlDb:/var/lib/mysqlDb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: productsgql
volumes:
  mysqlDb: